# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-MozEmbed
version:      0.06
version_from: MozEmbed.pm
installdirs:  site
requires:
    ExtUtils::Depends:             0.20
    ExtUtils::PkgConfig:           1.03
    Gtk2:                          1.081

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
